"torque":
  "log": ['RobotHardware0_tau']
  # "field": [[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11]]
  "field": [[4], [10]]
"tracking":
  "log": ['st_q', 'RobotHardware0_q', 'RobotHardware0_servoState']
  # "field": [[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11]]
  "field": [[4], [10]]
"joint_angle":
  "log": ['abc_q', 'st_q', 'el_q','RobotHardware0_q']
  "field": [[4], [10]]
"left_foot_force":
  "log": ['rmfo_off_rfsensor']
  "field": [[2]]
"left_foot_force":
  "log": ['sh_lfsensorOut', 'RobotHardware0_lfsensor', 'rmfo_off_lfsensor']
  "field": [[2]]
"contactStates":
  "log": ['abc_contactStates', 'abc_controlSwingSupportTime']
  "field": [[0],[1]]
